[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@solady-tokens/=lib/solady/src/tokens/",
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
]
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 20_000
# via_ir = true # Uncomment to use via IR

[profile.solx]
solc_version = "../solx"
