[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
remappings = [
    "@solady-tokens/=lib/solady/src/tokens/",
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
]

[profile.solx]
solc_version = "../solx"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
